on:
  push:
    branches:
      - main
  pull_request:
name: dprint check
jobs:
  check-style:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
          mise run format:check
  fix-style:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Create missing thumbnails and fix letters
        run: |
          mise run thumbnail
          mise run fix
      - name: Fix formatting
        run: |
          mise run format:fix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes and thumbnail generation
